"""
Zachary Williams
Problem 2: Even Fibonacci Numbers
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.

Example:
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with (1) and (2), the first terms
will be: (1), (2), (3), (5), (8), (13), (21), (34), (55), (89)
"""
four_mil = 4000000
a, b = 1, 2
sum = 0
while True:
    if a > four_mil or b > four_mil:
        break
    if b % 2 == 0:
        sum += b
    a, b = b, a + b
if __name__ == '__main__':
    answer = sum
    print(answer)
